app = "berkshirebot"

kill_signal = "SIGINT"
kill_timeout = 30

[env]
PORT = "7860"

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]





    
