app = "berkshirebot"

kill_signal = "SIGINT"
kill_timeout = 30

[env]
PORT = "7860"

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[deploy]
  strategy = "immediate"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1





    
